# EDA on Mexico epidemiology project

In [1]:
import pandas as pd 

df = pd.read_csv("/Users/hjk2160@columbia.edu/Desktop/main - epidimeology/epidemiology_project/Datastores/mexico_covid19.csv")

In [2]:
df.head()

,id,FECHA_ARCHIVO,ID_REGISTRO,ENTIDAD_UM,ENTIDAD_RES,RESULTADO,DELAY,ENTIDAD_REGISTRO,ENTIDAD,ABR_ENT,...,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263007 entries, 0 to 263006
Data columns (total 41 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   263007 non-null  int64
 1   FECHA_ARCHIVO        263007 non-null  object
 2   ID_REGISTRO          263007 non-null  object
 3   ENTIDAD_UM           263007 non-null  int64
 4   ENTIDAD_RES          263007 non-null  int64
 5   RESULTADO            263007 non-null  int64
 6   DELAY                263007 non-null  int64
 7   ENTIDAD_REGISTRO     263007 non-null  int64
 8   ENTIDAD              263007 non-null  object
 9   ABR_ENT              263007 non-null  object
 10  FECHA_ACTUALIZACION  263007 non-null  object
 11  ORIGEN               263007 non-null  int64
 12  SECTOR               263007 non-null  int64
 13  SEXO                 263007 non-null  int64
 14  ENTIDAD_NAC          263007 non-null  int64
 15  MUNICIPIO_RES        263001 non-null  float64
 16  TIPO_PACIENTE        263007 non-null  int64
 17  FECHA_INGRESO        263007 non-null  object
 18  FECHA_SINTOMAS       263007 non-null  object
 19  FECHA_DEF            263007 non-null  object
 20  INTUBADO             263007 non-null  int64
 21  NEUMONIA             263007 non-null  int64
 22  EDAD                 263007 non-null  int64
 23  NACIONALIDAD         263007 non-null  int64
 24  EMBARAZO             263007 non-null  int64
 25  HABLA_LENGUA_INDIG   263007 non-null  int64
 26  DIABETES             263007 non-null  int64
 27  EPOC                 263007 non-null  int64
 28  ASMA                 263007 non-null  int64
 29  INMUSUPR             263007 non-null  int64
 30  HIPERTENSION         263007 non-null  int64
 31  OTRA_COM             263007 non-null  int64
 32  CARDIOVASCULAR       263007 non-null  int64
 33  OBESIDAD             263007 non-null  int64
 34  RENAL_CRONICA        263007 non-null  int64
 35  TABAQUISMO           263007 non-null  int64
 36  OTRO_CASO            263007 non-null  int64
 37  MIGRANTE             263007 non-null  int64
 38  PAIS_NACIONALIDAD    263007 non-null  object
 39  PAIS_ORIGEN          263007 non-null  object
 40  UCI                  263007 non-null  int64
dtypes: float64(1), int64(30), object(10)
memory usage: 82.3+ MB

In [4]:
df.isnull().sum()

id                     0
FECHA_ARCHIVO          0
ID_REGISTRO            0
ENTIDAD_UM             0
ENTIDAD_RES            0
RESULTADO              0
DELAY                  0
ENTIDAD_REGISTRO       0
ENTIDAD                0
ABR_ENT                0
FECHA_ACTUALIZACION    0
ORIGEN                 0
SECTOR                 0
SEXO                   0
ENTIDAD_NAC            0
MUNICIPIO_RES          6
TIPO_PACIENTE          0
FECHA_INGRESO          0
FECHA_SINTOMAS         0
FECHA_DEF              0
INTUBADO               0
NEUMONIA               0
EDAD                   0
NACIONALIDAD           0
EMBARAZO               0
HABLA_LENGUA_INDIG     0
DIABETES               0
EPOC                   0
ASMA                   0
INMUSUPR               0
HIPERTENSION           0
OTRA_COM               0
CARDIOVASCULAR         0
OBESIDAD               0
RENAL_CRONICA          0
TABAQUISMO             0
OTRO_CASO              0
MIGRANTE               0
PAIS_NACIONALIDAD      0
PAIS_ORIGEN            0
UCI                    0
dtype: int64

In [6]:
df["MUNICIPIO_RES"].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
263002    False
263003    False
263004    False
263005    False
263006    False
Name: MUNICIPIO_RES, Length: 263007, dtype: bool

In [10]:
df = df.dropna(subset=['MUNICIPIO_RES'])

In [11]:
df.isnull().sum()

id                     0
FECHA_ARCHIVO          0
ID_REGISTRO            0
ENTIDAD_UM             0
ENTIDAD_RES            0
RESULTADO              0
DELAY                  0
ENTIDAD_REGISTRO       0
ENTIDAD                0
ABR_ENT                0
FECHA_ACTUALIZACION    0
ORIGEN                 0
SECTOR                 0
SEXO                   0
ENTIDAD_NAC            0
MUNICIPIO_RES          0
TIPO_PACIENTE          0
FECHA_INGRESO          0
FECHA_SINTOMAS         0
FECHA_DEF              0
INTUBADO               0
NEUMONIA               0
EDAD                   0
NACIONALIDAD           0
EMBARAZO               0
HABLA_LENGUA_INDIG     0
DIABETES               0
EPOC                   0
ASMA                   0
INMUSUPR               0
HIPERTENSION           0
OTRA_COM               0
CARDIOVASCULAR         0
OBESIDAD               0
RENAL_CRONICA          0
TABAQUISMO             0
OTRO_CASO              0
MIGRANTE               0
PAIS_NACIONALIDAD      0
PAIS_ORIGEN            0
UCI                    0
dtype: int64

# Data analysis: 

1. Data preprocessing.
2. Data visualization.
3. Regression analysis - (Linear, Logistic) / LATER Random Forest (classification/ tree models) 

#### EDA - 1번과 2번. Deadline - 8월30일.